import { z } from "zod";

export const modelConfigSchema = z.object({
  baseURL: z.string().default("https://api.deepseek.com"),
  model: z.string().default("deepseek-v4-flash"),
  temperature: z.number().min(0).max(2).default(0.2),
  timeoutMs: z.number().int().positive().default(60000),
});

export const recordingConfigSchema = z.object({
  enabled: z.boolean(),
  saveDirectoryName: z.string(),
  saveDirectoryPath: z.string().default(""),
  filenamePattern: z.string(),
  qualityPreset: z.enum(["original", "1080p", "720p", "480p"]),
  frameRate: z.union([z.literal(15), z.literal(30), z.literal(60)]),
  videoBitrateKbps: z.number().int().min(500).max(100000),
  recordSystemAudio: z.boolean(),
  recordMicrophone: z.boolean(),
  microphoneDeviceName: z.string(),
  audioMode: z.enum(["mixed", "separate"]),
  captureCursor: z.boolean(),
  hidePetWhenRecording: z.boolean(),
});

export const appConfigSchema = z.object({
  model: modelConfigSchema,
  shortcuts: z.object({
    captureArea: z.string(),
    openTranslator: z.string(),
    quickTranslateSelection: z.string(),
    togglePet: z.string(),
    toggleRecording: z.string(),
  }),
  translator: z.object({
    defaultSourceLanguage: z.string(),
    defaultTargetLanguages: z.array(z.string()),
    historyLimit: z.number().int().min(0).max(100),
  }),
  screenshot: z.object({
    hidePetWhenCapturing: z.boolean(),
    saveDirectoryName: z.string(),
    saveDirectoryPath: z.string().default(""),
    filenamePattern: z.string(),
    copyFormat: z.enum(["png"]),
    saveFormat: z.enum(["png", "jpeg"]).default("png"),
    jpegQuality: z.number().int().min(1).max(100).default(92),
    captureDelayMs: z.number().int().min(0).max(2000).default(90),
    defaultAnnotationColor: z.string(),
    enableScrollingCaptureExperiment: z.boolean(),
  }),
  recording: recordingConfigSchema,
  vitals: z.object({
    enabled: z.boolean().default(true),
    /** `always` pins the card on screen, `click` shows it on demand, `hidden` keeps it off. */
    hudMode: z.enum(["always", "click", "hidden"]).default("click"),
    notifications: z.boolean().default(true),
    satietyDecayPerHour: z.number().min(0).max(40).default(4.2),
    moodDecayPerHour: z.number().min(0).max(40).default(3),
    affinityDecayPerHour: z.number().min(0).max(40).default(0.6),
    /** Drag-and-drop position of the floating card; null means "follow the pet". */
    hudPosition: z.object({ x: z.number(), y: z.number() }).nullable().default(null),
  }),
  ocr: z.object({
    mode: z.enum(["local", "model"]),
    languages: z.array(z.string()),
    sendToTranslatorAfterRecognize: z.boolean(),
  }),
  pet: z.object({
    defaultHeight: z.number().int().min(96).max(480),
    opacity: z.number().min(0.3).max(1),
    alwaysOnTop: z.boolean(),
    wanderEnabled: z.boolean(),
    animationSpeed: z.number().min(0.5).max(2),
    skinSourcePath: z.string().default(""),
  }),
  chat: z.object({
    personalityId: z.string(),
    promptTemplateId: z.string(),
    customPrompt: z.string(),
    historyLimit: z.number().int().min(0).max(200),
    memoryEnabled: z.boolean(),
    proactiveTopicsEnabled: z.boolean(),
    proactiveTopicMinMinutes: z.number().int().min(1).max(1440),
    proactiveTopicMaxMinutes: z.number().int().min(1).max(1440),
  }),
  plugins: z.record(z.boolean()),
});

export type AppConfig = z.infer<typeof appConfigSchema>;

export const defaultAppConfig: AppConfig = {
  model: {
    baseURL: "https://api.deepseek.com",
    model: "deepseek-v4-flash",
    temperature: 0.2,
    timeoutMs: 60000,
  },
  shortcuts: {
    captureArea: "CommandOrControl+Shift+A",
    openTranslator: "CommandOrControl+Shift+T",
    quickTranslateSelection: "CommandOrControl+Shift+Y",
    togglePet: "CommandOrControl+Shift+P",
    toggleRecording: "CommandOrControl+Shift+R",
  },
  translator: {
    defaultSourceLanguage: "auto",
    defaultTargetLanguages: ["zh-CN", "en", "ja"],
    historyLimit: 20,
  },
  screenshot: {
    hidePetWhenCapturing: true,
    saveDirectoryName: "screenshots",
    saveDirectoryPath: "",
    filenamePattern: "lacritomato-yyyyMMdd-HHmmss",
    copyFormat: "png",
    saveFormat: "png",
    jpegQuality: 92,
    captureDelayMs: 90,
    defaultAnnotationColor: "#ff4d4f",
    enableScrollingCaptureExperiment: true,
  },
  recording: {
    enabled: true,
    saveDirectoryName: "recordings",
    saveDirectoryPath: "",
    filenamePattern: "lacritomato-recording-yyyyMMdd-HHmmss",
    qualityPreset: "1080p",
    frameRate: 30,
    videoBitrateKbps: 8000,
    recordSystemAudio: true,
    recordMicrophone: false,
    microphoneDeviceName: "",
    audioMode: "mixed",
    captureCursor: true,
    hidePetWhenRecording: true,
  },
  ocr: {
    mode: "local",
    languages: ["chi_sim", "eng"],
    sendToTranslatorAfterRecognize: false,
  },
  vitals: {
    enabled: true,
    hudMode: "click",
    notifications: true,
    satietyDecayPerHour: 4.2,
    moodDecayPerHour: 3,
    affinityDecayPerHour: 0.6,
    hudPosition: null,
  },
  pet: {
    defaultHeight: 224,
    opacity: 1,
    alwaysOnTop: true,
    wanderEnabled: false,
    animationSpeed: 1,
    skinSourcePath: "",
  },
  chat: {
    personalityId: "warm-companion",
    promptTemplateId: "daily-companion",
    customPrompt: "",
    historyLimit: 200,
    memoryEnabled: true,
    proactiveTopicsEnabled: true,
    proactiveTopicMinMinutes: 20,
    proactiveTopicMaxMinutes: 60,
  },
  plugins: {
    translator: true,
    screenshot: true,
    chat: true,
    recording: true,
  },
};